In [46]:
#importing libraries
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

#loading data
dataset=load_dataset('lukebarousse/data_jobs')

#converting the loaded dataset into a pandas dataframe
df=dataset['train'].to_pandas()

#formatting datetime
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
#creating a new dataframe with non-NaN average yearly salaries
new_df=df[df['salary_year_avg'].notna()].copy()
new_df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [48]:
#creating a function that multiplies the salary values with an inflation rate of 1.03
def new_salary(salary):
    return 1.03 * salary

In [49]:
#Applying the function using the .apply() function
new_df['salary_inflation']= new_df['salary_year_avg'].apply(new_salary)
new_df[['salary_year_avg','salary_inflation']]

        salary_year_avg  salary_inflation
28             109500.0         112785.00
77             140000.0         144200.00
92             120000.0         123600.00
100            228222.0         235068.66
109             89000.0          91670.00
...                 ...               ...
785624         139216.0         143392.48
785641         150000.0         154500.00
785648         221875.0         228531.25
785682         157500.0         162225.00
785692         157500.0         162225.00

[22003 rows x 2 columns]

In [ ]:
#using lambda() function
new_df['salary_inflation']= new_df['salary_year_avg'].apply(lambda salary: salary * 1.03)
new_df[['salary_year_avg','salary_inflation']]

        salary_year_avg  salary_inflation
28             109500.0         112785.00
77             140000.0         144200.00
92             120000.0         123600.00
100            228222.0         235068.66
109             89000.0          91670.00
...                 ...               ...
785624         139216.0         143392.48
785641         150000.0         154500.00
785648         221875.0         228531.25
785682         157500.0         162225.00
785692         157500.0         162225.00

[22003 rows x 2 columns]

In [56]:
#creating a custom function that converts the job skills column from string format into list
import ast
def clean_list(skills):
    if pd.notna(skills):
        return ast.literal_eval(skills)

In [57]:
#applying clean_list() using apply()
new_df['job_skills']=new_df['job_skills'].apply(clean_list)

In [65]:
#verifying if the job_skills column has been cleaned
type(new_df['job_skills'][28])

list

In [ ]:
#performing this cleaning using lambda()
df['job_skills']=df['job_skills'].apply(lambda skills: ast.literal_eval(skills) if pd.notna(skills) else skills)

In [ ]:
#verifying if the job_skills column has been cleaned
type(df['job_skills'][1])

list

In [73]:
#creating a function that goes through the job titles, mutiplies the salary with an inflation rate of 1.05 if 'senior' is found in the job title, else mutiplies it with 1.03
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return 1.05*row['salary_year_avg']
    else:
        return 1.03*row['salary_year_avg']

In [ ]:
#Applying the created function
new_df['salary_inflation']=new_df.apply(projected_salary, axis=1)
new_df[['job_title_short','salary_year_avg','salary_inflation']].head(25)

          job_title_short  salary_year_avg  salary_inflation
28         Data Scientist         109500.0         112785.00
77          Data Engineer         140000.0         144200.00
92          Data Engineer         120000.0         123600.00
100        Data Scientist         228222.0         235068.66
109          Data Analyst          89000.0          91670.00
116        Data Scientist         114000.0         117420.00
146         Data Engineer         129500.0         133385.00
180          Data Analyst          90250.0          92957.50
212        Data Scientist         157500.0         162225.00
257        Data Scientist         103128.0         106221.84
307         Data Engineer         185000.0         190550.00
339         Data Engineer         195000.0         200850.00
380         Data Engineer          97500.0         100425.00
388         Data Engineer          89000.0          91670.00
410          Data Analyst         133285.0         137283.55
450        Data Scientist         157500.0         162225.00
495  Senior Data Engineer         168500.0         176925.00
520      Business Analyst          63000.0          64890.00
545         Data Engineer          80000.0          82400.00
571         Data Engineer         110000.0         113300.00
573  Senior Data Engineer         160000.0         168000.00
645      Business Analyst         125000.0         128750.00
654         Data Engineer          70000.0          72100.00
657  Senior Data Engineer         165000.0         173250.00
679     Software Engineer         317000.0         326510.00

In [ ]:
#using lambda()
new_df['salary_inflation']=new_df.apply(lambda row:1.05 * row['salary_year_avg'] if 'Senior' in row['job_title_short'] else 1.03 * row['salary_year_avg'], axis =1)
new_df[['job_title_short', 'salary_year_avg', 'salary_inflation']].head(25)

          job_title_short  salary_year_avg  salary_inflation
28         Data Scientist         109500.0         112785.00
77          Data Engineer         140000.0         144200.00
92          Data Engineer         120000.0         123600.00
100        Data Scientist         228222.0         235068.66
109          Data Analyst          89000.0          91670.00
116        Data Scientist         114000.0         117420.00
146         Data Engineer         129500.0         133385.00
180          Data Analyst          90250.0          92957.50
212        Data Scientist         157500.0         162225.00
257        Data Scientist         103128.0         106221.84
307         Data Engineer         185000.0         190550.00
339         Data Engineer         195000.0         200850.00
380         Data Engineer          97500.0         100425.00
388         Data Engineer          89000.0          91670.00
410          Data Analyst         133285.0         137283.55
450        Data Scientist         157500.0         162225.00
495  Senior Data Engineer         168500.0         176925.00
520      Business Analyst          63000.0          64890.00
545         Data Engineer          80000.0          82400.00
571         Data Engineer         110000.0         113300.00
573  Senior Data Engineer         160000.0         168000.00
645      Business Analyst         125000.0         128750.00
654         Data Engineer          70000.0          72100.00
657  Senior Data Engineer         165000.0         173250.00
679     Software Engineer         317000.0         326510.00